name: 'Deploy Binaries'
description: 'Deploy assets to a GitHub release.'
author: 'Sardelka9515'

branding:
  icon: 'grid'
  color: 'purple'

inputs:
  upload_url:
    description: 'GitHub upload URL'
    required: true
  release_id:
    description: 'GitHub release id'
    required: true
  asset_path:
    description: 'Path to archive to upload'
    required: true
  asset_content_type:
    description: 'Content type of the uploaded file'
    required: true

runs:
  using: 'node12'
  main: 'index.js'
